export function useConstants() {
  const navigation = [
    {
      id: 1,
      name: "About",
      href: "/about",
    },
    {
      id: 2,
      name: "Skills",
      href: "/skills",
    },
    // {
    //   id: 3,
    //   name: "Works",
    //   href: "/works",
    // },
    // {
    //   id: 4,
    //   name: "Projects",
    //   href: "/projects",
    // },
    {
      id: 5,
      name: "Contact",
      href: "/contact",
    },
  ];

  const skillWithLogo = [
    {
      imgUrl: "/logos/html5-original.svg",
      name: "HTML",
      alt: "HTML logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/css3-plain-wordmark.svg",
      name: "CSS",
      alt: "CSS logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/javascript-original.svg",
      name: "JavaScript",
      alt: "JavaScript logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/vuejs-original.svg",
      name: "Vue",
      alt: "Vue logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/nuxtjs-original.svg",
      name: "NuxtJS",
      alt: "NuxtJS logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/react-original.svg",
      name: "React",
      alt: "React logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/tailwindcss-plain.svg",
      name: "TailwindCSS",
      alt: "TailwindCSS logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/firebase-plain.svg",
      name: "Firebase",
      alt: "Firebase logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/typescript-original.svg",
      name: "TypeScript",
      alt: "TypeScript logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/nodejs-original.svg",
      name: "NodeJS",
      alt: "NodeJS logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/git-original.svg",
      name: "Git",
      alt: "Git logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/threejs.png",
      name: "ThreeJS",
      alt: "ThreeJS logo",
      width: 150,
      height: 150,
    },
    {
      imgUrl: "/logos/gsap.png",
      name: "Gsap",
      alt: "Gsap logo",
      width: 150,
      height: 150,
    },
  ];
  const projects = [
    {
      isReverse: true,
      title: "Personal Blog",
      titleColor: "text-white",
      filterColor: "bg-slate-900 bg-opacity-60",
      imageUrl: "/project-ss/blog-page.png",
      description:
        "A personal blog using NextJS and Notion API. It has code syntax highlight, text to speech and image viewer.",
      techStack: [
        "NextJS",
        "TS",
        "TailwindCSS",
        "@notionhq/client",
        "highlight.js",
        "fslightbox-react",
      ],
      isUrl: true,
      urlLink: "https://blog.eazypau.com/",
      githubLink: "https://github.com/sharma-jai/my-blog",
    },
    {
      isReverse: true,
      title: "Order Management App",
      titleColor: "text-white",
      filterColor: "bg-slate-900 bg-opacity-60",
      imageUrl: "/project-ss/oms-order-page.png",
      description:
        "An order creation and management web app. It can be use to manage orders and prodcuts.",
      techStack: [
        "NextJS",
        "TS",
        "TailwindCSS",
        "daisyUI",
        "Firebase",
        "@tanstack/react-query",
        "@tanstack/react-table",
        "MomentJs",
        "formik",
        "lodash",
        "yup",
      ],
      isUrl: true,
      urlLink: "https://order-management-drab.vercel.app/",
    },
    {
      isReverse: false,
      title: "Eazy Chat App",
      titleColor: "text-white",
      filterColor: "bg-slate-900 bg-opacity-60",
      imageUrl: "/project-ss/chatapp-ss.webp",
      description:
        "A scalable real-time chat app designed to send and receive messages from users.",
      techStack: [
        "Vue",
        "TS",
        "Vite",
        "TailwindCSS",
        "Firebase",
        "Pinia",
        "Vue-router",
      ],
      isUrl: true,
      urlLink: "https://eazy-chat-app.netlify.app/login",
      githubLink: "https://github.com/sharma-jai/chatApp",
    },
    {
      isReverse: true,
      title: "Spotify Clone",
      titleColor: "text-white",
      filterColor: "bg-slate-500 mix-blend-hard-light",
      imageUrl: "/project-ss/spotify-ss.webp",
      description:
        "A Spotify clone web app. Built to view your saved and created playlist. It also can control your Spotify app playback state.",
      techStack: [
        "Vue",
        "Vite",
        "TailwindCSS",
        "Vuex",
        "Vue-router",
        "Spotify Web API",
      ],
      isUrl: false,
      githubLink: "https://github.com/sharma-jai/spotify-clone-web",
    },
    {
      isReverse: false,
      title: "Shopping Cart",
      titleColor: "text-white",
      filterColor: "bg-slate-700 bg-opacity-60",
      imageUrl: "/project-ss/shopping-cart-ss.webp",
      description:
        "A static E-Commerce website to demonstrate the flow of a user purchase",
      techStack: ["React", "SASS", "React-router"],
      isUrl: true,
      urlLink: "https://eazypau.github.io/shopping-cart-react/#/",
      githubLink: "https://github.com/sharma-jai/shopping-cart-react",
    },
    {
      isReverse: true,
      title: "Kanban Board",
      titleColor: "text-white",
      filterColor: "bg-slate-800 bg-opacity-60",
      imageUrl: "/project-ss/kanban-board.webp",
      description: "A Kanban board to store the user's task list.",
      techStack: [
        "React",
        "SASS",
        "TailwindCSS",
        "Local Storage",
        "React-beautiful-dnd",
      ],
      isUrl: true,
      urlLink: "https://eazypau.github.io/kanban-board-react/",
      githubLink: "https://github.com/sharma-jai/kanban-board-react",
    },
    {
      isReverse: false,
      title: "Saloon Booking Web",
      titleColor: "text-white",
      filterColor: "bg-slate-900 bg-opacity-60",
      imageUrl: "/project-ss/saloonbooking-ss.webp",
      description:
        "A door-to-door saloon appointment booking website allows users to book their appointment at any time.",
      techStack: [
        "Vue",
        "TS",
        "Vite",
        "TailwindCSS",
        "Firebase",
        "Vuex",
        "Vue-router",
      ],
      isUrl: true,
      urlLink: "https://saloonbooking-95d49.web.app/",
      githubLink: "https://github.com/sharma-jai/saloonbooking",
    },
    {
      isReverse: true,
      title: "Tic Tac Toe",
      titleColor: "text-white",
      filterColor: "bg-zinc-700 mix-blend-hard-light",
      imageUrl: "/project-ss/tictactoe-ss.webp",
      description: "A game of tic tac toe in HTML, CSS, and JavaScript.",
      techStack: ["HTML", "CSS", "JavaScript"],
      isUrl: true,
      urlLink: "https://eazypau.github.io/tictactoe/",
      githubLink: "https://github.com/sharma-jai/tictactoe",
    },
  ];


  // new timeline
  const timeline = [
    {
      companyName: "Zensar Technologies",
      duration: "Jan 2021 - Current",
      jobScope: [
        "Web Interface Design and Implementation: Designed and implemented efficient, scalable, and accessible web interfaces aimed at optimizing user experience.",
        "Framework Expertise: Extensive proficiency in utilizing Nuxt.js for frontend development, ensuring robust and performant applications.",
        "API Integration: Demonstrated success in integrating RESTful APIs into diverse client-side projects, enhancing functionality and interactivity.",
        "Optimization Strategies: Implemented caching mechanisms and optimized code and asset delivery for both REST APIs and server-side applications, employing strategies like lazy loading to improve performance significantly.",
        "Agile Methodologies: Proficient in agile development methodologies such as Scrum and Design Thinking, emphasizing continuous integration, testing, and iterative development practices.",
        "Cloud Proficiency: Hands-on experience with cloud environments, particularly Azure Cloud, enabling seamless deployment and scaling of applications.",
      ],
    },
    {
      companyName: "Dewlogics",
      duration: "May 2020 - December 2020",
      jobScope: [
        "Responsive Web Design: Implemented responsive design across multiple web applications using modern frameworks like React JS, ensuring optimal viewing experiences across various devices and screen sizes.",
        "Framework Expertise: Proficient in utilizing open-source toolkits such as MaterialUI and ReactBootstrap to streamline development and enhance user interface design.",
        "API Integration: Experienced in integrating Google APIs including Distance Matrix and Directions Matrix, enhancing application functionality and user interaction with location-based services.",
        "Animation Expertise: Leveraged GSAP (GreenSock Animation Platform) and Three.js libraries to create dynamic and visually appealing animations, enriching user interfaces and improving engagement.",
        "CI/CD Deployment: Established CI/CD deployment pipelines on Azure, ensuring efficient and automated deployment processes that enhance development speed and reliability.",
      ],
    },
    {
      companyName: "Saachi Technologies",
      duration: "January 2020 - April 2020",
      jobScope: [
        "Mobile Architecture Expertise: Extensive experience in developing scalable, high-quality products for production environments.",
        "Best Practices in Cross-Platform Development: Strong focus on implementing reusable designs and best practices in cross-platform applications.",
        "UI Component Design: Skilled in crafting complex UI components with expertise in CSS, animations, orchestration, and responsiveness.",
        "State Management Proficiency: Proficient in managing application states using frameworks like Redux for robust functionality.",
        "Push Notifications Implementation: Implemented Firebase API for Push Notifications to boost user engagement and retention.",
        "Cross-Platform Development: Developed performance-optimized React Native applications ensuring superior user experience across platforms.",
        "RESTful API Development: Created Node.js based RESTful APIs, establishing seamless data retrieval and manipulation endpoints.",
        "Google APIs Integration: Integrated Geolocation, Direction Matrix, and Distance Matrix APIs for enhanced location-based services and data insights.",
      ],
    },
  ];

  return {
    navigation,
    skillWithLogo,
    projects,
    timeline,
  };
}
